{
  description = "couldinho NixOS systems (base/desktop/laptop/dev)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    disko = {
      url = "github:nix-community/disko";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Tracks master rather than a release tag - v0.4.1 pinned to a nixpkgs
    # revision old enough that `boot.bootspec.enable` (which that release
    # still sets) has since been removed from nixpkgs entirely, breaking
    # `nix flake check` outright. master tracks nixpkgs-unstable.
    lanzaboote = {
      url = "github:nix-community/lanzaboote";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Prebuilt nix-index database (regenerated by this project's own CI) -
    # backs `, <command>` (comma) and the command-not-found shell hook in
    # modules/profiles/base.nix, without needing to build the index locally.
    nix-index-database = {
      url = "github:Mic92/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, disko, lanzaboote, nix-index-database, ... }:
    let
      system = "x86_64-linux";

      overlay = import ./pkgs;

      # Personal values (currently just a GPG key ID/URL - see
      # modules/options.nix and home/programs/gpg-import.nix) don't belong in
      # this public repo. Lives outside the repo entirely (not just
      # gitignored) - Nix flakes only evaluate files tracked by git, so a
      # gitignored-and-untracked local.nix at the repo root was silently
      # invisible to flake evaluation no matter what it contained. Reading
      # from $HOME requires --impure (see README.md's rebuild command).
      #
      # $HOME alone breaks under the documented `sudo nixos-rebuild switch`
      # (README.md/bootstrap.sh) - confirmed on real hardware, sudo does not
      # preserve HOME here (no env_keep+=HOME), so it resolves to /root
      # instead, /root/.config/couldinho/local.nix has never existed
      # (bootstrap.sh only ever copies local.nix into the *primary* user's
      # home, never root's), and couldinho.user et al silently come back
      # unset deep in dependent modules. sudo does always set SUDO_USER
      # itself though (unaffected by env_reset - it's not inherited from the
      # caller's environment), so fall back to that user's home when the
      # plain $HOME path doesn't exist.
      homeLocalPath = builtins.getEnv "HOME" + "/.config/couldinho/local.nix";
      sudoUser = builtins.getEnv "SUDO_USER";
      sudoUserLocalPath = "/home/" + sudoUser + "/.config/couldinho/local.nix";
      localPath =
        if builtins.pathExists homeLocalPath then homeLocalPath
        else if sudoUser != "" && builtins.pathExists sudoUserLocalPath then sudoUserLocalPath
        else homeLocalPath;
      localModule = nixpkgs.lib.optional (builtins.pathExists localPath) localPath;

      mkHost = { hostName, extraModules ? [ ] }:
        nixpkgs.lib.nixosSystem {
          inherit system;
          specialArgs = { inherit self; };
          modules = [
            { nixpkgs.overlays = [ overlay ]; }
            disko.nixosModules.disko
            lanzaboote.nixosModules.lanzaboote
            home-manager.nixosModules.home-manager
            nix-index-database.nixosModules.default
            ./modules/options.nix
            ./modules/secure-boot.nix
            ./modules/luks-common.nix
            ./hosts/${hostName}
            { networking.hostName = hostName; }
          ] ++ localModule ++ extraModules;
        };
    in
    {
      overlays.default = overlay;

      nixosConfigurations = {
        # Dual-monitor sway desktop: base + desktop + dev
        desktop = mkHost { hostName = "desktop"; };

        # Proxmox VM used to develop/test the desktop host before deploying
        # to the real machine above - see hosts/desktop-vm's own comments.
        desktop-vm = mkHost { hostName = "desktop-vm"; };

        # HiDPI sway laptop: base + desktop + laptop + dev
        laptop = mkHost { hostName = "laptop"; };
      };
    };
}
