#!/usr/bin/zsh

#System services
# - pcscd.service
# - lightdm.service
# - snapper-cleanup.timer
# - strongswan.service
# - usbguard.service
# - usbguard-dbus.service
#
#User services
# - dunst.service
# - yubikey-touch-detector.service
#
#
#Steps
# - DONE: Add custom repo to sources
# - DONE: Install packages
# - Link/copy config files
# - Start services
# - Add Strongswan config
#   - Trust & add certs (maybe request USB key?)
#   - Add to connman/networkmanager?
#   - change perms 

set -e
exec 2> >(while read line; do echo -e "\e[01;31m$line\e[0m"; done)

system_options=(base desktop)

script_name="$(basename "$0")"
dotfiles_dir="$(cd "$(dirname "$0")"; pwd)"
cd "$dotfiles_dir"

systemctl_enable_start() {
  if [ "$#" -eq 1 ]; then
    target="system"
    name="$1"
  else
    target="$1"
    name="$2"
  fi
  if [[ "$target" == "user" ]]; then
    echo "systemctl --user enable --now "$name""
    systemctl --user enable --now "$name"
  else
    echo "systemctl enable --now "$name""
    systemctl enable --now "$name"
  fi
}

if [ "$(whoami)" != "root" ]; then

    system_sel=$(printf '%s\n' "${system_options[@]}" | fzy)

    cd stow
    if [[ $system_sel == "base" ]]; then
        echo "Choosing base"
        stow -v -t $HOME base
    fi

    if [[ $system_sel == "desktop" ]]; then
        echo "Choosing desktop"
        stow -v -t $HOME base
        stow -v -t $HOME desktop
    fi
    cd ..
fi
