post_install() {
    post_upgrade
}

post_upgrade() {

    # System environment variables
    system=laptop
    curr_system=$(cat /etc/environment.d/80-couldinho-system 2>/dev/null)
    if [[ "${curr_system}" != *"${system}"* ]]; then
        echo "Adding ${system} to /etc/environment.d/80-couldinho-system"
        echo "Current system = ${curr_system}"
        echo "COULDINHO_SYSTEM=${system},${curr_system}" \
            > /etc/environment.d/80-couldinho-system
    fi
}
